### ISSUE TITLE
MYSQL_DATABASE don't working

### ISSUE THREAD

**Issue by jcthalys** [docker-library/mysql#353]
I trying run with this command and is not creating the database
Am I doing something wrong?

docker run --name listavip-mysql -p 3306:3306 -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes MYSQL_DATABASE=listavip" -d mysql

`
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'listavip'
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
      `

**Comment by yosifkit** [comment]
You need to have two `-e` arguments to pass in two environment variables.

```
docker run --name listavip-mysql -p 3306:3306 -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" -e "MYSQL_DATABASE=listavip" -d mysql
